# -*- coding: utf-8 -*-
"""Untitled-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140GV6-wEBr_a-LMMwED355vjVqj9bOOM
"""

import os
import sys
from pathlib import Path
import pandas as pd
import glob
from datetime import time, datetime, timedelta
import re
import ipywidgets as widgets
from IPython.display import display, Image, clear_output
import numpy as np
import shutil

# 画像フォルダのパスを指定
INPUT_IMAGE_DIR = r"C:\Users\daimu\dev\project\nakashibetsu1"
# アノテーション結果を保存するCSVファイル
csv_file = os.path.join(INPUT_IMAGE_DIR, "annotationsV4.csv")

# ラベルごとの保存先フォルダを作成
output_dirs = {
    1: os.path.join(INPUT_IMAGE_DIR, "level1"),
    2: os.path.join(INPUT_IMAGE_DIR, "level2"),
    3: os.path.join(INPUT_IMAGE_DIR, "level3")
}
for dir_path in output_dirs.values():
    os.makedirs(dir_path, exist_ok=True)

try:
    df = pd.read_csv(csv_file)
except FileNotFoundError:
    print(f"情報: {csv_file} が見つかりません。画像フォルダからDataFrameを新規作成します。")
    image_files = [f for f in os.listdir(INPUT_IMAGE_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    if not image_files:
        print(f"エラー: {INPUT_IMAGE_DIR} 内に画像ファイルが見つかりません。")
        raise

    # 日付情報がファイル名にあれば、それを元にソートする（画像の表示順を一定にするため）
    data = []
    for f in image_files:
        match = re.match(r'(\d{8})_(\d{6})', f)
        if match:
            dt_str = f"{match.group(1)}{match.group(2)}"
            dt_obj = datetime.strptime(dt_str, '%Y%m%d%H%M%S')
            data.append({'datetime': dt_obj, 'image_name': f})
        else:
            # 日付情報がなくてもリストには追加
            data.append({'datetime': datetime.fromtimestamp(os.path.getctime(os.path.join(INPUT_IMAGE_DIR, f))), 'image_name': f})

    df = pd.DataFrame(data)
    df = df.sort_values('datetime').reset_index(drop=True)

# datetime列はソートにのみ使用し、表示はしない
if 'datetime' in df.columns:
    df['datetime'] = pd.to_datetime(df['datetime'])

# アノテーション列を初期化
if 'annotation_level' not in df.columns:
    df['annotation_level'] = 0
if 'time_of_day' not in df.columns:
    df['time_of_day'] = 0 # 0: 未選択, 1: 昼, 2: 夜

# current_indexを全体で共有
current_index = 0

# 日付関連のウィジェットを削除
prev_image_button = widgets.Button(description="< 前の画像", icon='chevron-left', layout=widgets.Layout(width='auto'))
next_image_button = widgets.Button(description="次の画像 >", icon='chevron-right', layout=widgets.Layout(width='auto'))
progress_label = widgets.HTML(value="", layout=widgets.Layout(margin='0 20px'))
save_button = widgets.Button(description="CSVと画像を保存", icon='save', button_style='success')
save_status = widgets.Label(value="")
output_area = widgets.Output()


def update_dataframe(df_index, column_name, new_value):
    global df
    value_to_set = int(new_value)
    df.loc[df_index, column_name] = value_to_set
    save_status.value = "未保存"

def update_display():
    global df, current_index
    with output_area:
        clear_output(wait=True)
        # daily_dfをdfに変更
        total_images = len(df)

        if total_images == 0:
            progress_label.value = f"<h3>画像がありません</h3>"
            prev_image_button.disabled = True
            next_image_button.disabled = True
            return

        row = df.iloc[current_index]
        # original_df_indexはcurrent_indexと等価
        original_df_index = current_index

        try:
            image_path = os.path.join(INPUT_IMAGE_DIR, row['image_name'])
            with open(image_path, 'rb') as f:
                image_data = f.read()
            img_widget = widgets.Image(value=image_data, width=900)
        except (FileNotFoundError, IOError):
            img_widget = widgets.Label(
                value=f"画像なし:\n{row['image_name']}",
                layout=widgets.Layout(width='900px', height='500px', border='1px solid grey', justify_content='center', align_items='center')
            )

        info_label = widgets.HTML(value=f"<h3>{row['image_name']}</h3>")
        left_column = widgets.VBox([img_widget, info_label], layout=widgets.Layout(align_items='center', padding='10px'))

        level_options_map = {'未選択': 0, 'Level 1': 1, 'Level 2': 2, 'Level 3': 3}
        current_level = row.get('annotation_level', 0)
        current_level_label = next((label for label, value in level_options_map.items() if value == current_level), '未選択')

        level_radio_buttons = widgets.RadioButtons(
            options=level_options_map.keys(),
            value=current_level_label,
            description='レベル:',
            disabled=False,
            layout=widgets.Layout(width='auto')
        )
        def on_level_radio_change(change, df_idx=original_df_index):
            if change['type'] == 'change' and change['name'] == 'value':
                selected_value = level_options_map[change['new']]
                update_dataframe(df_idx, 'annotation_level', selected_value)
        level_radio_buttons.observe(on_level_radio_change, names='value')

        tod_options_map = {'未選択': 0, '昼': 1, '夜': 2}
        current_tod = row.get('time_of_day', 0)
        current_tod_label = next((label for label, value in tod_options_map.items() if value == current_tod), '未選択')

        tod_radio_buttons = widgets.RadioButtons(
            options=tod_options_map.keys(),
            value=current_tod_label,
            description='時間帯:',
            disabled=False,
            layout=widgets.Layout(width='auto', margin='20px 0 0 0')
        )
        def on_tod_radio_change(change, df_idx=original_df_index):
            if change['type'] == 'change' and change['name'] == 'value':
                selected_value = tod_options_map[change['new']]
                update_dataframe(df_idx, 'time_of_day', selected_value)
        tod_radio_buttons.observe(on_tod_radio_change, names='value')

        right_column = widgets.VBox([level_radio_buttons, tod_radio_buttons], layout=widgets.Layout(padding='10px', justify_content='center'))
        display(widgets.HBox([left_column, right_column]))
        progress_label.value = f"<h3>{current_index + 1} / {total_images} 枚目</h3>"
        prev_image_button.disabled = (current_index == 0)
        next_image_button.disabled = (current_index >= total_images - 1)

# 日付関連のハンドラを削除
def on_prev_image_clicked(b):
    global current_index
    if not prev_image_button.disabled:
        current_index -= 1
        update_display()

def on_next_image_clicked(b):
    global current_index
    if not next_image_button.disabled:
        current_index += 1
        update_display()

def on_save_button_clicked(b):
    save_status.value = "保存中..."
    try:
        df_copy = df.copy()
        if 'annotation_level' in df_copy.columns:
            df_copy['annotation_level'] = df_copy['annotation_level'].fillna(0).astype(int)
        if 'time_of_day' in df_copy.columns:
            df_copy['time_of_day'] = df_copy['time_of_day'].fillna(0).astype(int)

        # datetime列はCSVに保存しない場合は、ここでdropする
        if 'datetime' in df_copy.columns:
            df_copy = df_copy.drop(columns=['datetime'])

        df_copy.to_csv(csv_file, index=False, encoding='utf-8-sig')

        copied_count = 0
        error_count = 0
        for index, row in df.iterrows():
            level = row['annotation_level']
            image_name = row['image_name']
            if level in output_dirs:
                source_path = os.path.join(INPUT_IMAGE_DIR, image_name)
                destination_dir = output_dirs[level]
                destination_path = os.path.join(destination_dir, image_name)
                try:
                    if os.path.exists(source_path):
                        shutil.copy(source_path, destination_path)
                        copied_count += 1
                    else:
                        print(f"警告: 元画像が見つかりません: {source_path}")
                        error_count += 1
                except Exception as e:
                    print(f"エラー: ファイルコピーに失敗しました。 {e}")
                    error_count += 1

        timestamp = datetime.now().strftime('%H:%M')
        if error_count > 0:
            save_status.value = f"CSV保存, 画像コピーで{error_count}件エラー ({timestamp})"
        else:
            save_status.value = f"CSVと画像{copied_count}枚を保存 ({timestamp})"
    except Exception as e:
        save_status.value = f"保存失敗: {e}"


prev_image_button.on_click(on_prev_image_clicked)
next_image_button.on_click(on_next_image_clicked)
save_button.on_click(on_save_button_clicked)

image_nav_controls = widgets.HBox([
    prev_image_button,
    progress_label,
    next_image_button,
    save_button,
    save_status
], layout=widgets.Layout(justify_content='center', align_items='center', margin='10px 0'))

app_layout = widgets.VBox([
    image_nav_controls,
    output_area,
])

display(app_layout)

update_display()